/*
    일대다 관계의 테이블 생성
    
    1. 명칭
        1) 부모 테이블 : 일(1), PK를 가진 테이블
        2) 자식 테이블 : 다(M), FK를 가진 테이블
    2. 생성
        부모 테이블을 먼저 생성하고, 자식 테이블을 나중에 생성
    3. 삭제
        자식 테이블을 먼저 삭제하고, 부모 테이블을 나중에 삭제
*/

-- 학교 테이블
-- 부모 테이블 : PK를 가진 테이블(관계를 맺을때)
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER(1) NOT NULL PRIMARY KEY,    --최대 한자리 숫자
    SCH_NAME VARCHAR(20 BYTE) NOT NULL  -- NAME은 STRING처리가 필요하므로 VARCHAR 사용
);

DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER(1) NOT NULL,   
    SCH_NAME VARCHAR(20 BYTE) NOT NULL,
    PRIMARY KEY(SCH_CODE)
);

DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER(1) NOT NULL CONSTRAINT PK_SCHOOL PRIMARY KEY,
    SCH_NAME VARCHAR(20 BYTE) NOT NULL 
);

DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER(1) NOT NULL,   
    SCH_NAME VARCHAR(20 BYTE) NOT NULL,
    CONSTRAINT PK_SCHOOL PRIMARY KEY(SCH_CODE)
);

-- 학생테이블
-- 자식 테이블 : FK를 가진 테이블
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY,
    SCH_CODE NUMBER(1) NOT NULL REFERENCES SCHOOL(SCH_CODE),    -- SCHOOL 테이블에 CODE를 가지게 된다.    -- SCHOOL이 부모, STUDENT가 자식이 됨.
    STU_NAME VARCHAR2(20 BYTE) NULL
);

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL,
    SCH_CODE NUMBER(1) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE) NULL,
    PRIMARY KEY(STU_NO),
    FOREIGN KEY(SCH_CODE) REFERENCES SCHOOL(SCH_CODE)
);

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL PRIMARY, 
    SCH_CODE NUMBER(1) NOT NULL,    
    STU_NAME VARCHAR2(20 BYTE) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO),
    CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY(SCH_CODE) REFERENCES SCHOOL(SCH_CODE)
);

-- 최종 정리
-- 생성 : 부모 먼저, 자식 나중
-- 삭제 : 자식 먼저, 부모 나중
DROP TABLE STUDENT;
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCH_CODE NUMBER(1) NOT NULL,   
    SCH_NAME VARCHAR(20 BYTE) NOT NULL,
    CONSTRAINT PK_SCHOOL PRIMARY KEY(SCH_CODE)
);
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL PRIMARY, 
    SCH_CODE NUMBER(1) NOT NULL,    
    STU_NAME VARCHAR2(20 BYTE) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO),
    CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY(SCH_CODE) REFERENCES SCHOOL(SCH_CODE)
);


-- M:N 관계
DROP TABLE REQUEST;
DROP TABLE STUDENT2;
DROP TABLE SUBJECT;
CREATE TABLE STUDENT2(
    STU2_CODE NUMBER(5) NOT NULL,
    STU2_NAME VARCHAR(30 BYTE) NOT NULL,
    STU2_AGE NUMBER(3) NOT NULL,
    CONSTRAINT PK_STUDENT2 PRIMARY KEY(STU2_CODE)
);
CREATE TABLE SUBJECT(
    SUB_CODE VARCHAR2(2 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(30 BYTE) NOT NULL,
    SUB_ADMNAME VARCHAR2(30 BYTE) NOT NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
);
CREATE TABLE REQUEST(
    REQ_CODE NUMBER(1) NOT NULL,
    STU2_CODE NUMBER(5) NOT NULL,
    SUB_CODE VARCHAR(2 BYTE) NOT NULL,
    CONSTRAINT PK_REQUEST PRIMARY KEY(REQ_CODE),
    CONSTRAINT FK_REQUEST_STUDENT2 FOREIGN KEY(REQ_CODE) REFERENCES STUDENT2(STU2_CODE),
    CONSTRAINT FK_REQUEST_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE) 
);