-- 수강신청 데이터베이스 구축

/* 테이블 삭제*/

-- 외래키를 가진 테이블을 먼저 삭제해야 함(자식 테이블을 먼저 삭제)
DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
-- 외래키가 없는 테이블을 나중에 삭제(부모 테이블을 나중에 삭제)
DROP TABLE COURSE;
DROP TABLE PROFESSOR;

/*테이블 생성*/

CREATE TABLE PROFESSOR (
    PRO_NO    NUMBER            NOT NULL,  -- 기본키
    PRO_NAME  VARCHAR2(30 BYTE) NULL,
    PRO_MAJOR VARCHAR2(30 BYTE) NULL
);

CREATE TABLE COURSE (
    COUR_NO   NUMBER            NOT NULL,  -- 기본키
    COUR_NAME VARCHAR2(30 BYTE) NULL,
    COUR_UNIT NUMBER(1)         NULL
);

CREATE TABLE  STUDENT (
    STU_NO    NUMBER             NOT NULL,  -- 기본키
    STU_NAME  VARCHAR2(30 BYTE)  NULL,
    STU_ADDR  VARCHAR2(100 BYTE) NULL,
    STU_GRADE NUMBER(1)          NULL,
    PRO_NO    NUMBER             NOT NULL  -- PROFESSOR 테이블의 P_NO칼럼을 참조하는 외래키
);
    
CREATE TABLE ENROLL (
    ENR_NO    NUMBER NOT NULL,
    STU_NO    NUMBER NOT NULL,  -- STUDENT 테이블의 S_NO 칼럼을 참조하는 외래키
    COUR_NO   NUMBER NOT NULL,  -- COURSE 테이블의 C_NO 칼럼을 참조하는 외래키
    ENR_RQDAY DATE   NULL
);

CREATE TABLE LECTURE (
    LEC_NO   NUMBER            NOT NULL,  -- 기본키
    PRO_NO   NUMBER            NOT NULL,  -- PROFESSOR 테이블의 PRO_NO 칼럼을 참조하는 외래키
    ENR_NO   NUMBER            NOT NULL,  -- ENROLL 테이블의 ENR_NO 칼럼을 참조하는 외래키
    LEC_NAME VARCHAR2(30 BYTE) NULL,
    LEC_ROOM VARCHAR2(30 BYTE) NULL
);

-- 기본기 추가
ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NO);
ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE COURSE ADD CONSTRAINT PK_COURSE PRIMARY KEY(COUR_NO);
ALTER TABLE ENROLL ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO);
ALTER TABLE LECTURE ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NO);

-- 외래키 추가
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COUR_NO)
        REFERENCES COURSE(COUR_NO)
            ON DELETE CASCADE;
            
ALTER TABLE LECTURE 
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENR_NO)
        REFERENCES ENROLL(ENR_NO)
            ON DELETE CASCADE;
            
 




