DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE COURSE;
DROP TABLE ENROLL;
DROP TABLE LECTURE;

-- 테이블 생성
CREATE TABLE STUDENT (
    STU_NO VARCHAR2(15 BYTE) NOT NULL,
    STU_NAME VARCHAR2(15 BYTE) NULL,
    STU_ADDR VARCHAR2(30 BYTE) NULL,
    STU_GRADE NUMBER(1) NULL,
    STU_PROFTEL VARCHAR2(30 BYTE) NULL UNIQUE
);

CREATE TABLE PROFESSOR (
    PRO_TEL VARCHAR2(30 BYTE) NOT NULL UNIQUE,
    PRO_NAME VARCHAR2(15 BYTE) NULL,
    PRO_MAJOR VARCHAR2(15 BYTE) NULL
);

CREATE TABLE COURSE (
    COUR_NO NUMBER NOT NULL,
    COUR_NAME VARCHAR2(15 BYTE) NULL,
    COUR_SCORE CHAR(1 BYTE) NULL
);
    
CREATE TABLE ENROLL (
    ENR_NO VARCHAR2(15 BYTE) NOT NULL UNIQUE,
    STU_NO VARCHAR2(15 BYTE) NOT NULL,
    COUR_NO NUMBER NOT NULL,
    ENR_RQDAY VARCHAR2(15 BYTE) NULL
);

CREATE TABLE LECTURE (
    LEC_NO NUMBER NOT NULL,
    PRO_TEL VARCHAR2(30 BYTE) NOT NULL UNIQUE,
    ENR_NO VARCHAR2(15 BYTE) NOT NULL UNIQUE,
    LEC_NAME VARCHAR2(15 BYTE),
    LEC_ROOM VARCHAR2(15 BYTE)
);

-- 기본기 추가
ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_TEL);
ALTER TABLE COURSE ADD CONSTRAINT PK_COURSE PRIMARY KEY(COUR_NO);
ALTER TABLE ENROLL ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO);
ALTER TABLE LECTURE ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NO);

-- 외래키 추가
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COUR_NO)
        REFERENCES COURSE(COUR_NO)
            ON DELETE CASCADE;
            
ALTER TABLE LECTURE 
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENR_NO)
        REFERENCES ENROLL(ENR_NO)
            ON DELETE CASCADE;
            
 




