-- 테이블 스페이스
CREATE TABLESPACE TEMP_SPACE    -- 테이블 이름 : TEMP_SPACE
DATAFILE 'C:/temp/temp.dbf'
SIZE 1M;  -- 1MB는 1M로 표시

-- 테이블 스페이스 삭제
DROP TABLESPACE TEMP_SPACE;
DROP TABLESPACE TEMP_SPACE
    INCLUDING CONTENTS;
DROP TABLESPACE TEMP_SPACE
    INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TEMP_SPACE      -- 전부 삭제
    INCLUDING CONTENTS AND DATAFILES
        CASCADE CONSTRAINTS;
        